INSERT INTO Famille (id, nomfamille) VALUES (1, '22');
INSERT INTO Famille (id, nomfamille) VALUES (2, 'Ananas');
INSERT INTO Famille (id, nomfamille) VALUES (3, 'Avengers');
INSERT INTO Famille (id, nomfamille) VALUES (4, 'Brochet');
INSERT INTO Famille (id, nomfamille) VALUES (5, 'Captain');
INSERT INTO Famille (id, nomfamille) VALUES (6, 'Champagne');
INSERT INTO Famille (id, nomfamille) VALUES (7, 'Chasseur');
INSERT INTO Famille (id, nomfamille) VALUES (8, 'Cons');
INSERT INTO Famille (id, nomfamille) VALUES (9, 'Cooper');
INSERT INTO Famille (id, nomfamille) VALUES (10, 'Daleux');
INSERT INTO Famille (id, nomfamille) VALUES (11, 'Doc');
INSERT INTO Famille (id, nomfamille) VALUES (12, 'ECC');
INSERT INTO Famille (id, nomfamille) VALUES (13, 'Harem');
INSERT INTO Famille (id, nomfamille) VALUES (14, 'Insestada');
INSERT INTO Famille (id, nomfamille) VALUES (15, 'Manita');
INSERT INTO Famille (id, nomfamille) VALUES (16, 'Melka');
INSERT INTO Famille (id, nomfamille) VALUES (17, 'Meltin Potes');
INSERT INTO Famille (id, nomfamille) VALUES (18, 'Miclo Pd');
INSERT INTO Famille (id, nomfamille) VALUES (19, 'Nombreux');
INSERT INTO Famille (id, nomfamille) VALUES (20, 'Paillette');
INSERT INTO Famille (id, nomfamille) VALUES (21, 'Richter, les meilleurs');
INSERT INTO Famille (id, nomfamille) VALUES (22, 'Saka');
INSERT INTO Famille (id, nomfamille) VALUES (23, 'Saoul');
INSERT INTO Famille (id, nomfamille) VALUES (24, 'Shamrock');
INSERT INTO Famille (id, nomfamille) VALUES (25, 'Shark');
INSERT INTO Famille (id, nomfamille) VALUES (26, 'Viperine');

INSERT INTO Residence (id, name) VALUES (1, 'Jarlard 1');
INSERT INTO Residence (id, name) VALUES (2, 'Jarlard 2');
INSERT INTO Residence (id, name) VALUES (3, 'Jarlard 3');
INSERT INTO Residence (id, name) VALUES (4, 'Jarlard 4');
INSERT INTO Residence (id, name) VALUES (5, 'Jarlard 5');
INSERT INTO Residence (id, name) VALUES (6, 'Gambetta 1');
INSERT INTO Residence (id, name) VALUES (7, 'Gambetta 2');
INSERT INTO Residence (id, name) VALUES (8, 'Temporalité');
INSERT INTO Residence (id, name) VALUES (9, 'Halfon');
INSERT INTO Residence (id, name) VALUES (10, 'Montaigne');

INSERT INTO PartieCommune(id, name, localisation_id) VALUES (1, 'V10', 1);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (2, 'V11', 1);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (3, 'V12', 1);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (4, 'V13', 1);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (5, 'V20', 2);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (6, 'V21', 2);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (7, 'V22', 2);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (8, 'V23', 2);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (9, 'V30', 3);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (10, 'V31', 3);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (11, 'V32', 3);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (12, 'V33', 3);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (13, 'V40', 4);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (14, 'V41', 4);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (15, 'V42', 4);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (16, 'V43', 4);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (17, 'Carré 50', 5);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (18, 'Carré 51', 5);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (19, 'Carré 52', 5);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (20, 'Carré 53', 5);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (21, 'Salle TV Gambet 1', 6);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (21, 'Carré du 80', 7);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (22, 'Carré du 81', 7);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (21, 'Salle TV Gambet 2', 7);
INSERT INTO PartieCommune(id, name, localisation_id) VALUES (21, 'Barbecue', 7);
